name: "Security Static Analysis"

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
    - main
    - master
  schedule:
  - cron: '48 0 2 * *'
jobs:
  scan:
    name: "Security Static Analysis"
    runs-on: ubuntu-latest

    # Skip any PR created by dependabot:
    if: (github.actor != 'dependabot[bot]')

    steps:
    - uses: scout24/s24-sast-action@v2
      with:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

